# Generated by Django 3.2.4 on 2021-07-02 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_auto_20210702_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariocontacto',
            name='mensaje',
            field=models.TextField(verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='comentariocontacto',
            name='usuario',
            field=models.TextField(verbose_name='Usuario'),
        ),
    ]
